### ISSUE TITLE
Container restarting exit code: 132

### ISSUE THREAD

**Issue by ganey** [cloudamqp/amqproxy#174]
Hi,

We're running this as a kubernetes Daemonset (we've also tried sidecar/extraContainers) and containers constantly restart

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: amqproxy
  labels:
    name: amqpproxy
    instance: amqproxy
spec:
  selector:
    matchLabels:
      name: amqproxy
  template:
    metadata:
      labels:
        name: amqproxy
    spec:
      containers:
        - name: amqproxy
          image: cloudamqp/amqproxy:v2.0.2
          env:
            - name: AMQP_URL
              value: {{ .Values.amqproxy.upstreamUrl }}
          ports:
            - name: amqpproxy
              containerPort: 5673
              protocol: TCP
              hostPort: 5673
```

The logs aren't great, even if we try turning on debug

```
2024-09-10T14:42:23.082393Z  INFO amq_proxy.server Proxy upstream: someurl.rmq.cloudamqp.com:5671 TLS
2024-09-10T14:42:23.082475Z  INFO amq_proxy.server Proxy listening on 0.0.0.0:5673
2024-09-10T14:42:23.240688Z  INFO amq_proxy.channel_pool[remote_address: "10.42.23.249:57192"] Adding upstream connection
```

the container then dies all the time with exist code 132:

```
terminated
Reason:Reason: Error - exit code: 132
```

Any suggestions?
