### ISSUE TITLE
UNEXPECTED_FRAME - expected content header for class 60, got non content header frame instead 

### ISSUE THREAD

**Issue by oceanho** [cloudamqp/amqproxy#59]
hi, I am use
client: amqplib 0.7.1 , https://www.npmjs.com/package/amqplib
rabbitmq-server: 3.7
It's will got the fllowing error on my client

`UNEXPECTED_FRAME - expected content header for class 60, got non content header frame instead`

any idea, thanks.

This is my docker-compose yaml file of mq deploy.
``` yaml
version: "3.7"
services:
  mq-n1:
    image: rabbitmq:3.7-management
    hostname: rabbit-c1
    network_mode: host
    restart: always
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbit-cookie
      - RABBITMQ_DEFAULT_USER=private
      - RABBITMQ_DEFAULT_PASS=private
  mq-proxy:
    image: cloudamqp/amqproxy
    network_mode: host
    restart: always
    command: amqp://127.0.0.1:5672 --port=55672
```
